version: "3"
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    # - flask run --host=0.0.0.0
    environment:
    - FLASK_APP=hello.py
    - app.debug=True
    ports:
    - "5000:5000"
    volumes:
    - ./:/root